### ISSUE TITLE
Starting tip failed consistency check

### ISSUE THREAD

**Issue by ThomasBouquet95** [ioiobzit/iota-nelson-node#19]
Hi,

I am trying to send a transaction using the js library and being connect to my iota nelson node. I got the following error : 

Error: Request Error: starting tip failed consistency check: SWLTULJIWPOPOCPSVCTDXRDGHKHCARGGY9NMMLQW9DEBNTZRNYVGTXZK9ZXSXMACQHPSNEZDFUNV99999
    at Object.requestError (/home/pi/IOTACOFFEE/iota.lib.js/lib/errors/requestErrors.js:11:12)
    at makeRequest.prepareResult (/home/pi/IOTACOFFEE/iota.lib.js/lib/utils/makeRequest.js:293:24)
    at exports.XMLHttpRequest.request.onreadystatechange (/home/pi/IOTACOFFEE/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at exports.XMLHttpRequest.dispatchEvent (/home/pi/IOTACOFFEE/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/pi/IOTACOFFEE/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/pi/IOTACOFFEE/iota.lib.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)

**Comment by ThomasBouquet95** [comment]
According to https://github.com/iotaledger/iri/issues/375 I am not full sync after 12h ... I don't understand why

**Comment by ioiobzit** [comment]
Hello,

please verify with the IRI project or try following solution from iota.partners:

http://iota.partners/#database

All the best.
Antonio
