### ISSUE TITLE
Nelson Monitor cannot connect to nelson

### ISSUE THREAD

**Issue by henningvs** [ioiobzit/iota-nelson-node#20]
After I run the described setup I get the following error when I try to access http://MYPIP:3000
I changed nothing except for the configuration files according to the README.

```
Nelson Monitor
Error while connecting to Nelson
Error: Received erroneous response from Nelson
    at Request._callback (/usr/src/nelson.mon/routes/index.js:22:30)
    at Request.self.callback (/usr/src/nelson.mon/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/src/nelson.mon/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/src/nelson.mon/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```
![image](https://user-images.githubusercontent.com/5406293/37206522-397d5728-2399-11e8-9ea0-a2c9fcdea79f.png)

**Comment by firesurf** [comment]
Same here!

**Comment by jorisrymenants** [comment]
I have the same problem

**Comment by henningvs** [comment]
I got it working by adapting the docker compose file (See Pull Request #23). Also you have to use a different url schema:
`http://DockerHostIP:5000/#/<username>:<password>`
