### ISSUE TITLE
WARNING: Connection pool is full, discarding connection: localhost

### ISSUE THREAD

**Issue by Newinvestcoin** [ioiobzit/iota-nelson-node#28]
luc@luc-As:~/iota-nelson-node$ sudo docker-compose up -d
[sudo] пароль для luc: 
Recreating iota_prom-iotaexp
iota_prom-nodeexp is up-to-date
Recreating iota_nelson.cli
iota_nelson.gui is up-to-date
Recreating iota_field.cli
Recreating iota_iri
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
Recreating iota_prometheus
Recreating iota_grafana

and i don't see nothing in Grafana
say N/A on all windows

**Comment by Newinvestcoin** [comment]
reinstall all node 

work 22 hours and get this error
04/09 16:49:36.800 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[na:1.8.0_151]
	at java.util.ArrayList.get(ArrayList.java:433) ~[na:1.8.0_151]
	at zmq.socket.pubsub.Dist.distribute(Dist.java:161) ~[iri.jar:na]
	at zmq.socket.pubsub.Dist.sendToMatching(Dist.java:137) ~[iri.jar:na]
	at zmq.socket.pubsub.XPub.xsend(XPub.java:177) ~[iri.jar:na]
	at zmq.SocketBase.send(SocketBase.java:712) ~[iri.jar:na]
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:2588) ~[iri.jar:na]
	at org.zeromq.ZMQ$Socket.send(ZMQ.java:2562) ~[iri.jar:na]
	at com.iota.iri.zmq.MessageQ.publish(MessageQ.java:33) ~[iri.jar:na]
	at com.iota.iri.network.Node.lambda$null$2(Node.java:152) ~[iri.jar:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_151]
	at com.iota.iri.network.Node.lambda$null$3(Node.java:150) ~[iri.jar:na]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[na:1.8.0_151]
	at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$4(Node.java:148) ~[iri.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]


how fix?

**Comment by ioiobzit** [comment]
do no use root to run docker containers and try again

**Comment by ioiobzit** [comment]
Please also remember to change then nelson and field config.ini following the instructions
